#  MIT License
#
#  Copyright (c) 2021 - 2024 ViliusSutkus89.com
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

name: build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'
      - '!.github/workflows/testInner.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[SkipCI]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install --upgrade pip conan setuptools

      - run: |
          conan config install .github/conan
          conan profile list
          conan profile show

      - uses: actions/checkout@v4
        with:
          repository: ViliusSutkus89/conan-odr-index
          ref: pdf2htmlEX-with-dependency-tracking
          path: conan-odr-index

#      - uses: actions/cache@v4
#        with:
#          path: ~/.conan2
#          key: ${{ hashFiles('**') }}
#          restore-keys: conan-cache

      - run: python scripts/conan_export_all_packages.py
        working-directory: conan-odr-index

      - run: conan install . --output-folder=build/conan/armv7 --profile:host=android-21-armv7 --build=missing
        working-directory: pdf2htmlEX
      - run: conan install . --output-folder=build/conan/armv8 --profile:host=android-21-armv8 --build=missing
        working-directory: pdf2htmlEX
      - run: conan install . --output-folder=build/conan/x86 --profile:host=android-21-x86 --build=missing
        working-directory: pdf2htmlEX
      - run: conan install . --output-folder=build/conan/x86_64 --profile:host=android-21-x86_64 --build=missing
        working-directory: pdf2htmlEX

      - run: ./gradlew lintRelease publishToMavenLocal

      - uses: actions/upload-artifact@v4
        with:
          name: library-lint-report
          path: pdf2htmlEX/build/reports/lint-results-release.html
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: maven-local
          path: ~/.m2
          if-no-files-found: error

      - run: du -hs ~/.conan2/
      - run: du -hs ~/.conan2/p
      - run: du -hs ~/.conan2/p/b

  instrumentedTests-aosp_atd-target:
    name: android-${{ matrix.api-level }} on ${{ matrix.arch }} (${{ matrix.api-type-target }})
    needs: build
    strategy:
      fail-fast: false
      matrix:
        api-level:
          - 34
#          - 33
#          - 32
#          - 31
#          - 30
        arch: [x86_64]
        api-type-target: [aosp_atd]
        include:
          - api-level: 30
            arch: x86
            api-type-target: aosp_atd
    uses: ./.github/workflows/testInner.yml
    with:
      api-level: ${{ matrix.api-level }}
      arch: ${{ matrix.arch }}
      api-type-target: ${{ matrix.api-type-target }}

  instrumentedTests-default-target:
    name: android-${{ matrix.api-level }} on ${{ matrix.arch }} (${{ matrix.api-type-target }})
    needs: build
    strategy:
      fail-fast: false
      matrix:
        api-level:
#          - 29
#          - 28
#          - 27
#          - 26
#          - 25
#          - 24
          - 23
#          - 22
#          - 21
        arch:
#          - x86_64
          - x86
        api-type-target: [default]
    uses: ./.github/workflows/testInner.yml
    with:
      api-level: ${{ matrix.api-level }}
      arch: ${{ matrix.arch }}
      api-type-target: ${{ matrix.api-type-target }}
