#  MIT License
#
#  Copyright (c) 2021 - 2024 ViliusSutkus89.com
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

name: Instrumented Tests
run-name: Test on android-${{ inputs.api-level }} ${{ inputs.arch }} (${{ inputs.api-type-target }})
on:
  workflow_call:
    inputs:
      api-level:
        required: true
        type: string
      arch:
        required: true
        type: string
      api-type-target:
        required: true
        type: string

jobs:
  instrumentedTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install --upgrade pip conan setuptools

      - run: |
          conan config install .github/conan
          conan profile list
          conan profile show

      - uses: actions/cache/restore@v4
        with:
          path: ~/.conan2
          key: conan-cache

      - uses: actions/checkout@v4
        with:
          repository: ViliusSutkus89/conan-odr-index
          ref: pdf2htmlEX_and_deps
          path: conan-odr-index

      - run: python scripts/conan_export_all_packages.py
        working-directory: conan-odr-index

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          api-level: ${{ inputs.api-level }}
          arch: ${{ inputs.arch }}
          target: ${{ inputs.api-type-target }}
          sdcard-path-or-size: 1G
          disk-size: 8G
          emulator-boot-timeout: 1800
          script: |
            mkdir -p testResults/screenshots
            adb logcat > testResults/logcat.txt &

            adb shell screencap /data/local/tmp/beforeTests.png
            adb pull /data/local/tmp/beforeTests.png testResults/screenshots/

            ./gradlew connectedCheck || touch sorry_but_tests_are_failing
            adb pull /sdcard/Pictures/screenshots testResults/ || true

            adb shell screencap /data/local/tmp/afterTests.png
            adb pull /data/local/tmp/afterTests.png testResults/screenshots/

            mv pdf2htmlEX/build/reports/androidTests/connected testResults/
            mv pdf2htmlEX/build/outputs/androidTest-results testResults/

            test ! -f sorry_but_tests_are_failing

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testResults-${{ inputs.api-level }}-${{ inputs.arch }}-${{ inputs.api-type-target }}
          path: testResults
          if-no-files-found: error
